purchases_cardholder:
ifdef n
	python3 preparation/purchases_cardholder.py $(n)
else
	python3 preparation/purchases_cardholder.py
endif

onsite_valid:
	python3 preparation/onsite_valid.py

online_valid:
	python3 preparation/online_valid.py

onsite_state:
	python3 preparation/onsite_state.py

online_state:
	python3 preparation/online_state.py
