purchases_cardholder:
ifdef n
	python3 purchases_cardholder.py $(n)
else
	python3 purchases_cardholder.py
endif

onsite_valid:
	python3 onsite_valid.py

online_valid:
	python3 online_valid.py

onsite_state:
	python3 onsite_state.py

online_state:
	python3 online_state.py
